import * as admin from 'firebase-admin';

// Force Initialize Admin
if (!admin.apps.length) {
    try {
        admin.initializeApp();
        console.log("Admin initialized");
    } catch (e) {
        console.error("Admin init failed:", e);
        process.exit(1);
    }
}

async function runForensics() {
    const symbol = 'UMAC';
    const dateStr = '2025-12-04'; // YYYY-MM-DD
    const db = admin.firestore();

    console.log(`\n🔍 STARTING FORENSIC EVIDENCE COLLECTION FOR ${symbol} @ ${dateStr}`);

    // --- STEP 1: Evidence of API ---
    console.log("\n[STEP 1] DATA ACQUISITION (Yahoo API)");
    let price: number | null = null;
    try {
        // Use the robust instantiation logic we fixed in yahoo.ts
        let yf: any;
        try {
            // eslint-disable-next-line @typescript-eslint/no-var-requires
            const pkg = require('yahoo-finance2');
            if (typeof pkg.default === 'function') {
                yf = new pkg.default();
            } else if (typeof pkg === 'function') {
                yf = new pkg();
            } else {
                yf = pkg.default || pkg;
            }
        } catch (initErr: any) {
            throw new Error(`Failed to initialize yahoo-finance2: ${initErr.message}`);
        }

        // To search for 2025-12-04, we need a range that covers it.
        // Yahoo historical needs period1 (start) and period2 (end).
        // period1 = target date 00:00:00 UTC
        // period2 = target date + 1 day
        const d = new Date(dateStr);
        // Ensure UTC midnight
        const p1 = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate(), 0, 0, 0));
        const p2 = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + 1, 0, 0, 0)); // Next day

        const queryOptions = {
            period1: p1,
            period2: p2
        };

        console.log(`Requesting Yahoo Historical for ${symbol}:`, queryOptions);

        const result = await yf.historical(symbol, queryOptions);

        console.log(">>> [RAW EVIDENCE] YAHOO API RESPONSE: <<<");
        console.dir(result, { depth: null, colors: true });

        if (Array.isArray(result) && result.length > 0) {
            const candle = result[0];
            price = candle.close;
            console.log(`✅ Extracted Price: ${price}`);
        } else {
            console.warn("⚠️ API returned empty array or invalid format.");
        }

    } catch (e: any) {
        console.error("❌ [STEP 1 FAILED] API Error:", e);
    }

    // --- STEP 2: Evidence of DB Write ---
    console.log("\n[STEP 2] DATABASE PERSISTENCE (Firestore Write)");

    // Even if API failed, we test DB write with test data or null
    const writePrice = price || 123.45; // Fallback to prove DB works even if API fails
    const docId = `${dateStr}_${symbol}`;
    const docRef = db.collection('officialCloses').doc(docId);

    const payload = {
        symbol: symbol,
        date: dateStr,
        tradingDate: dateStr,
        close: writePrice,
        provider: 'forensic_test_script',
        status: 'ok',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        note: 'Generated by debug-evidence.ts'
    };

    try {
        console.log(`Attempting to write doc: ${docId}`, payload);
        await docRef.set(payload, { merge: true });
        console.log("Write operation completed. Verifying...");

        // IMMEDIATE READBACK
        const snapshot = await docRef.get();
        if (snapshot.exists) {
            console.log(">>> [RAW EVIDENCE] FIRESTORE DOCUMENT READBACK: <<<");
            console.dir(snapshot.data(), { depth: null, colors: true });
            console.log("✅ Database Write Verified.");
        } else {
            console.error("❌ [STEP 2 FAILED] Document wrote but cannot be found immediately.");
        }

    } catch (e: any) {
        console.error("❌ [STEP 2 FAILED] Database Error:", e);
    }

    console.log("\n🔍 FORENSIC ANALYSIS COMPLETE.");
    process.exit(0);
}

runForensics();
